<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.cobble-project</groupId>
        <artifactId>cobble-flink-monitor-build</artifactId>
        <version>${cobble.flink.base.version}-${patch.version}-SNAPSHOT</version>
        <relativePath>../cobble-flink-monitor-build/pom.xml</relativePath>
    </parent>
    <artifactId>cobble-flink-monitor</artifactId>
    <version>${cobble.flink.version.2.0}</version>
    <name>cobble-flink-monitor (Flink 2.0)</name>
    <properties>
        <flink.version>2.0.2</flink.version>
        <monitor.metadata.version>5</monitor.metadata.version>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-shade-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
